name: summarize_dirac_coefficients_test

on:
  push:
    paths:
      - "reference.**.out"
      - "**.py"
      - "sum_dirac_dfcoef"
      - ".github/workflows/**"

# Ref : https://github.com/pytest-dev/pytest/issues/7443#issue-650484842
env:
  PYTEST_ADDOPTS: "--color=yes"

defaults:
  run:
    shell: bash
jobs:
  test-linux:
    timeout-minutes: 5 # Max execution time (min)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Run unittest
        run: |
          pytest
